swagger: '2.0'
info:
  description: API used for Unattended ECR Connector
  version: 1.0.0
  title: Unattended ECR Connector

host: stage-secure-gateway.hipay-tpp.com
basePath: /rest/
schemes:
 - http
  
securityDefinitions:
  basicAuth:
    type: basic
# To apply Basic auth to the whole API:
security:
  - basicAuth: []
  
# tags are used for organizing operations
tags:
- name: merchants
  description: Operations available to merchant
- name: maintenance
  description: Maintenance calls
paths:
  /order:
    post:
      tags:
      - merchants
      summary: Creates an order for unattended terminal
      operationId: orderUnattendedTerminal
      description: |
        Initiate a payment on the unattended terminal. On case of success, create on order based on payment details and parameters send on the query.
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - in: body
        name: inventoryItem
        description: Inventory item to add
        schema:
          $ref: '#/definitions/OrderQuery'
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/OrderResponse'
        401:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/AuthentificationErrorResponse'
        599:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/ErrorResponse'
  
  /stop:
    get:
      tags:
      - maintenance
      summary: Stop terminal manager server
      operationId: stopTerminalManager
      description: Ask terminal manager server to stop properly as soon as possible
      produces:
        - application/json
      responses:
        200:
          description: OK
        599:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/ErrorResponse'
  /cancel:
    get:
      tags:
      - maintenance
      summary: Cancel current transaction
      operationId: cancelTransaction
      description: Ask terminal to cancel current transaction
      produces:
        - application/json
      responses:
        200:
          description: OK
        599:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/ErrorResponse'
  /reset:
    get:
      tags:
      - maintenance
      summary: Reset hardware terminal
      operationId: resetTerminal
      description: Ask terminal to make a reboot
      produces:
        - application/json
      responses:
        200:
          description: OK
        599:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/ErrorResponse'
  /version:
    get:
      tags:
      - maintenance
      summary: Get current version of terminal manager application
      operationId: versionTerminalManager
      description: Ask terminal manager to give the current application version running
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/VersionResponse'
        599:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/ErrorResponse'
  /config:
    get:
      tags:
      - maintenance
      summary: Get serial number of hardware terminal
      operationId: configTerminal
      description: Ask hardware terminal to return the serial number
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ConfigResponse'
        599:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/ErrorResponse'
  /tlc:
    get:
      tags:
      - maintenance
      summary: Data capture request (Telecollection)
      operationId: doTlc
      description: Transmit all transactions to acquire for all applications on the hardware terminal
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TlcResponse'
        599:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/ErrorResponse'
  /check:
    get:
      tags:
      - maintenance
      summary: Check hardware terminal status
      operationId: checkStatus
      description: Get current status on the hardware terminal
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CheckResponse'
        599:
          description: Invalid
          schema:
            type: array
            items:
              $ref: '#/definitions/ErrorResponse'
definitions:
  OrderQuery:
    type: object
    required:
    - amount
    - orderId
    properties:
      amount:
        type: integer
        description: Total order amount, calculated as the sum of purchased items, plus shipping fees (if present), plus tax fees (if present). The amount is expressed in the smallest unit of the currency (100 for 1€)
        example: 100
      orderId:
        type: string
        description: Order number of your request payment.
        example: Order_12345
      currency:
        type: string
        description: ISO 4217 alpha currency code.
        default: EUR
        example : EUR
      basket:
        $ref: '#/definitions/Basket'
      customer:
        $ref: '#/definitions/Customer'
      customData:
        $ref: '#/definitions/CustomData'
  Basket:
    description: Shopping cart details.
    required:
    - product_reference
    - type
    - quantity
    - name
    - unit_price
    - tax_rate
    - total_amount
    properties:
      european_article_numbering:
        type: string
        description: European article numbering.
        example: 4711892728946
      product_reference:
        type: string
        description: Unique product reference.
        example: NF-a1690
      type:
        type: string
        description: Type of product.
        enum: [good, discount, fee]
        example: good
      quantity:
        type: integer
        description: Product quantity.
        example: 1
      name:
        type: string
        description: Product description.
        example: My first product
      unit_price:
        type: number
        description: Unit price including taxes in order currency.
        example: 8.99
      tax_rate:
        type: number
        description: Tax rate in percentage.
        example: 0
      discount:
        type: number
        description: Discount amount, always 0 or negative.
        example: 0
      total_amount:
        type: number
        description: Unit price X quantity – discount. The sum of every “total_amount” must be equal to the “amount” sent in the call.
        example: 8.99
  Customer:
    description: Customer’s information object.
    properties:
      id:
        type: string
        description: Merchant's customer id.
        example: 283749291
      firstname:
        type: string
        description: The customer's first name.
        example: John
      lastname:
        type: string
        description: The customer's last name.
        example: Doe
      email:
        type: string
        description: The customer's e-mail address.
        example: johnDoe@test.com
  CustomData:
    description: In the custom data parameter, you can set all the values of you want to retrieve in HiPay’s backoffice.
    type: object
    additionalProperties: true
    example: {"shop":"Opera","vendor":"Mario","newCustomer":true,"event":42}
  OrderResponse:
    type: object
    required:
    - status 
    - amount
    - currency
    - orderId
    - basket
    - customer
    - customData
    properties:
      status:
        type: string
        description: Status received from the unattend terminal regarding the payment.
        example: Success
      error:
        type: string
        description: Error description.
        example: 
      receipt:
        $ref: '#/definitions/Receipt'
      ticket:
        type: string
        description: Customer ticket to be printed or sent by merchant. Pipes needs to be replaced by a new line.
        example: CARTE BANCAIRE|A0000000041010Mastercard|LE 28/11/19 A 11:06:17|HIPAY |92HIPAY |123456 39033123454322345|XXXXXXXXXXXX1234   1234567899765|001 000001 03 C |@|NO AUTO:122603|MONTANT REEL:1,00 EUR|MONTANT ESTIME:8,99 EUR|DEBIT|TICKET CLIENT A CONSERVER||
      amount:
        type: integer
        description: Total order amount, calculated as the sum of purchased items, plus shipping fees (if present), plus tax fees (if present). The amount is expressed in the smallest unit of the currency (100 for 1€)
        example: 100
      currency:
        type: string
        description: ISO 4217 alpha currency code.
        default: EUR
        example : EUR
      orderId:
        type: string
        description: Order number of your request payment.
        example: Order_12345
      basket:
        $ref: '#/definitions/Basket'
      customer:
        $ref: '#/definitions/Customer'
      customData:
        $ref: '#/definitions/CustomData'
      notificationHipaySent:
        type: boolean
        description: Indicates whether Hipay has been notified of the transaction.
        example: true
  Receipt:
    description: Receipt's information object.
    properties:
      ticketHeader:
        type: string
        description: Ticket Header of the transaction.
        example: "                    "
      localDate:
        type: string
        description: Local date of the transaction.
        example: "030420"
      localTime:
        type: string
        description: Local time of the transaction.
        example: "083011"
      acceptor:
        type: string
        description: Acceptor name and location.
        example: "HIPAY                                 92HIPAY             "
      transactionType:
        type: string
        description: Transaction type.
        example: "01"
      contractNumber:
        type: string
        description: merchant id (MID). Unique identifier assigned to the merchant.
        example: "123456"
      SIRET:
        type: string
        description: SIRET number.
        example: "12345678901234"
      activity:
        type: string
        description: Merchant Category Code (MCC).
        example: "5039"
      paymentType:
        type: string
        description: Payment type of the transaction.
        example: "46"
      siteType:
        type: string
        description: Site type.
        example: "        "
      primaryAccountNumber:
        type: string
        description: Masked Primary Account Number.
        example: "123456XXXXXX7890"
      TASA:
        type: string
        description: Acceptor System Application Type (TASA).
        example: "2046"
      cardAppExpiry:
        type: string
        description: Expiry date of card application.
        example: "221031"
      serviceCode:
        type: string
        description: Service code.
        example: "   "
      crypto:
        type: string
        description: Cryptogram.
        example: "1234567898765434"
      currencyNumCode:
        type: string
        description: Numerical currency code of the transaction.
        example: "978"
      acceptationSystemNum:
        type: string
        description: Acceptation system number (rank of the terminal).
        example: "001"
      transactionNumber:
        type: string
        description: Transaction number generated by the acceptor system.
        example: "000001"
      transactionFileNumber:
        type: string
        description: Transaction file number generated by the acceptor system.
        example: "000006"
      readingMode:
        type: string
        description: Reading mode of Primary account number.
        example: "C"
      authorizationNumber:
        type: string
        description: Authorization number of the transaction generated by the acquiror.
        example: "136967"
      forceCode:
        type: string
        description: Force code.
        example: " "
      amount:
        type: string
        description: Amount of the transaction expressed in the smallest unit of the currency and padded with zero
        example: "00000899"
      currencyAlphaCode:
        type: string
        description: ISO 4217 alpha currency code.
        example: "EUR"
      currencyFractionPart:
        type: string
        description: Fractional part of the currency.
        example: "2"
      counterValueAmount:
        type: string
        description: Amount of a transaction in counter value.
        example: "00005897"
      counterValueCurrencyAlphaCode:
        type: string
        description: Currency code of the counter value.
        example: "FRF"
      counterValueCurrencyFractionPart:
        type: string
        description: Fractional part of the counter value.
        example: "2"
      inclusiveAmount:
        type: string
        description: Inclusive amount.
        example: "00000899"
      ticketFooter:
        type: string
        description: Ticket footer of the transaction.
        example: "                                       "
      AID:
        type: string
        description: Application Identifier.
        example: "A0000000041010  "
      label:
        type: string
        description: Application Identifier name (card brand).
        example: "Mastercard      "
  VersionResponse:
    type: object
    required:
    - version
    - type
    - os
    properties:
      version:
        type: string
        description: Terminal manager application version
        example: "0.0.0-tpa-winserver2003_64"
      type:
        type: string
        enum: [tpa,tpe]
        example: tpa
        description: >
            Type of terminal manager application :
             * "tpa" - Unattended terminal (iSelf)
             * "tpe" - Attented terminal (Ingenico Move or Desk 5000, Verifone v420m, ...)
      os:
        type: string
        description: Operating system where terminal manager application is running
        example: winserver2003_64
  ConfigResponse:
    type: object
    required:
    - deviceId
    properties:
      deviceId:
        type: string
        description: Hardware device serial number 
        example: "00000012345678"
  TlcResponse:
    type: object
    required:
    - NbApp
    - App
    properties:
      NbApp:
        type: string
        description: Number of payment applications present on hardware terminal
        example: "1"
      App:
        type: array
        items:
          $ref: '#/definitions/AppTlcStatus'
  AppTlcStatus:
    type: object
    required:
    - Name
    - Status
    properties:
      Name:
        type: string
        description: Payment application name
        example: "CB EMV"
      Status:
        type: string
        example: "0"
        enum: ["0", "1", "2", "3"]
        description: >
            Payment application status :
             * "0" - data capture OK
             * "1" - data capture incomplete
             * "2" - Call error
             * "3" - No call
  CheckResponse:
    type: object
    required:
    - cr
    - card
    - call
    - periph
    properties:
      cr:
        type: string
        example: "0"
        enum: ["0", "1", "2", "3"]
        description: >
            Hardware terminal report status :
             * "0" - OK, terminal available
             * "1" - NO OK, terminal not available (busy)
             * "2" - Terminal in maintenance mode
             * "3" - Terminal not connected
      card:
          type: string
          example: "0"
          enum: ["0", "1"]
          description: >
              Card presence in contact reader :
               * "0" - No card
               * "1" - Card present
      call:
          type: string
          example: "0"
          enum: ["0", "1", "2"]
          description: >
              Call status :
               * "0" - Neither data capture nor parameters downloading in progress
               * "1" - Data capture in progress
               * "2" - Parameters downloading in progress
      periph:
          type: string
          example: "0"
          enum: ["0", "1", "2", "3"]
          description: >
            Hardware terminal periphal status :
             * "0" - OK
             * "1" - Pin-pad out of service, security activated
             * "2" - Reader out of service
             * "3" - Pin-pad and reader out of service
  ErrorResponse:
    type: object
    required:
    - error
    properties:
      error:
        type: string
        description: Error description
        example: "Connection time out"
  AuthentificationErrorResponse:
    type: object
    required:
    - error
    properties:
      error:
        type: string
        description: Error description
        example: "Public HiPay API credential error"
        